"""
Resemble AI Client

Client wrapper for Resemble AI's deepfake detection API.
"""

import asyncio
import base64
from typing import Any, Dict, Optional

import httpx

from src.shared.config import get_settings
from src.services.detection.base import BaseAPIClient


class ResembleAIClient(BaseAPIClient):
    """
    Client for Resemble AI's audio deepfake detection API.

    Resemble AI provides state-of-the-art voice cloning detection,
    identifying synthetic speech generated by various TTS systems.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        timeout: float = 30.0,
    ):
        settings = get_settings()
        self.api_key = api_key or settings.resemble_api_key
        self.base_url = base_url or "https://api.resemble.ai/v1"
        self.timeout = timeout
        self._client: Optional[httpx.AsyncClient] = None

    @property
    def name(self) -> str:
        return "resemble_ai"

    async def _get_client(self) -> httpx.AsyncClient:
        """Get or create HTTP client."""
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                },
                timeout=self.timeout,
            )
        return self._client

    async def close(self) -> None:
        """Close HTTP client."""
        if self._client and not self._client.is_closed:
            await self._client.aclose()
            self._client = None

    async def health_check(self) -> bool:
        """Check if Resemble AI API is available."""
        if not self.api_key:
            return False

        try:
            client = await self._get_client()
            response = await client.get("/status")
            return response.status_code == 200
        except Exception:
            return False

    async def analyze(
        self,
        audio_data: bytes,
        sample_rate: int = 16000,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Analyze audio for synthetic speech detection.

        Args:
            audio_data: Raw PCM audio bytes.
            sample_rate: Audio sample rate in Hz.
            **kwargs: Additional parameters.

        Returns:
            Analysis results from Resemble AI.
        """
        if not self.api_key:
            return {
                "error": "API key not configured",
                "is_synthetic": None,
                "confidence": 0.0,
            }

        try:
            client = await self._get_client()

            # Encode audio as base64
            audio_b64 = base64.b64encode(audio_data).decode("utf-8")

            payload = {
                "audio": audio_b64,
                "sample_rate": sample_rate,
                "format": kwargs.get("format", "pcm"),
                "detect_model": kwargs.get("detect_model", True),
            }

            response = await client.post("/detect/synthetic", json=payload)

            if response.status_code == 200:
                result = response.json()
                return {
                    "is_synthetic": result.get("is_synthetic", False),
                    "confidence": result.get("confidence", 0.0) * 100,  # Convert to 0-100
                    "model_detected": result.get("model_detected"),
                    "artifacts": result.get("artifacts", []),
                    "raw_response": result,
                }
            else:
                return {
                    "error": f"API error: {response.status_code}",
                    "is_synthetic": None,
                    "confidence": 0.0,
                }

        except httpx.TimeoutException:
            return {
                "error": "API timeout",
                "is_synthetic": None,
                "confidence": 0.0,
            }
        except Exception as e:
            return {
                "error": str(e),
                "is_synthetic": None,
                "confidence": 0.0,
            }

    async def analyze_voice_print(
        self,
        audio_data: bytes,
        reference_audio: bytes,
        sample_rate: int = 16000,
    ) -> Dict[str, Any]:
        """
        Compare audio against a reference voice print.

        Args:
            audio_data: Audio to analyze.
            reference_audio: Reference audio for comparison.
            sample_rate: Sample rate for both audio samples.

        Returns:
            Comparison results.
        """
        if not self.api_key:
            return {
                "error": "API key not configured",
                "is_match": None,
                "similarity": 0.0,
            }

        try:
            client = await self._get_client()

            payload = {
                "audio": base64.b64encode(audio_data).decode("utf-8"),
                "reference": base64.b64encode(reference_audio).decode("utf-8"),
                "sample_rate": sample_rate,
            }

            response = await client.post("/compare/voice", json=payload)

            if response.status_code == 200:
                result = response.json()
                return {
                    "is_match": result.get("is_match", False),
                    "similarity": result.get("similarity", 0.0) * 100,
                    "raw_response": result,
                }
            else:
                return {
                    "error": f"API error: {response.status_code}",
                    "is_match": None,
                    "similarity": 0.0,
                }

        except Exception as e:
            return {
                "error": str(e),
                "is_match": None,
                "similarity": 0.0,
            }
